version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: shopsense
      POSTGRES_USER: shopsense
      POSTGRES_PASSWORD: shopsense
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shopsense-net

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - shopsense-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - shopsense-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 > /dev/null 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - shopsense-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: shopsense
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - shopsense-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - shopsense-net

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      OLLAMA_MODEL: llama3.1:8b-q4_0
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - shopsense-net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
    networks:
      - shopsense-net

  api-gateway:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka
    networks:
      - shopsense-net

  user-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - shopsense-net

  product-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      ELASTICSEARCH_HOST: elasticsearch:9200
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    depends_on:
      - postgres
      - redis
      - kafka
      - elasticsearch
    networks:
      - shopsense-net

  price-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: price-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - shopsense-net

  review-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: review-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - shopsense-net

  ai-insights-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: ai-insights-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      OLLAMA_BASE_URL: http://ollama:11434
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    depends_on:
      - postgres
      - redis
      - kafka
      - ollama
    networks:
      - shopsense-net

  notification-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    depends_on:
      - postgres
      - redis
      - kafka
      - mailhog
    networks:
      - shopsense-net

  analytics-service:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.service
      args:
        SERVICE_NAME: analytics-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopsense
      SPRING_DATASOURCE_USERNAME: shopsense
      SPRING_DATASOURCE_PASSWORD: shopsense
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP: "kafka:9092"
      JWT_SECRET: ${JWT_SECRET:-d25tgtjowQ2BDDd__RSWJkIHWp8fqCye3PL1vI72swLpeXNXGLUZi2_3zpYsTenSjETrhWgBhyAHxoqcaBunRQ==}
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - shopsense-net

  nginx:
    image: nginx:1.25
    profiles: ["edge"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-gateway
    networks:
      - shopsense-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    profiles: ["observability"]
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - shopsense-net

  prometheus:
    image: prom/prometheus:v2.51.0
    profiles: ["observability"]
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - shopsense-net

  grafana:
    image: grafana/grafana:10.3.1
    profiles: ["observability"]
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - shopsense-net

  tempo:
    image: grafana/tempo:2.4.1
    profiles: ["observability"]
    networks:
      - shopsense-net

volumes:
  pgdata:
  redisdata:
  esdata:
  ollama-data:

networks:
  shopsense-net:
    driver: bridge
